# Generated by Django 3.2.5 on 2021-07-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchModel',
            new_name='Search',
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': 'Search', 'verbose_name_plural': 'Searches'},
        ),
    ]
